### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by cjevans76** [ParsePlatform/parse-embedded-sdks#20] opened 2015-04-15 20:11 UTC
Is there a worked example for periodically sending data from the yun up to parse?  I tried the code below, but the board froze after a while.  I used FreeMemory to look at the available memory and this seems to be the problem.  I suspect I'm just not clearing the ParseCreate object correctly.  Any tips?

#include <Bridge.h>
#include <Parse.h>
#include <MemoryFree.h>

#define INTERVAL 60000 // one minute in ms

ParseClient client;
static unsigned long lTimer;
void setup() {
  // put your setup code here, to run once:

  // Initialize digital pin 13 as an output.
  pinMode(13, OUTPUT);

  // Initialize Bridge
  Bridge.begin();

  // Initialize Parse
  client.begin("MY_KEY1", "MY_KEY2");

  // initialise minute timer
  lTimer = millis();

  // Initialize Serial
  Serial.begin(9600);
  Serial.println("Initialised");
}

void loop() {
  // timer
  if ( (long)( millis() - lTimer ) >= 0)
  {
    lTimer += INTERVAL;  // do it again 1 interval later
    //periodic actions

    // print memory state
    Serial.print("freeMemory()=");
    Serial.println(freeMemory());

    // create and fill parse object
    ParseObjectCreate create;
    create.setClassName("TestData");
    create.add("tStk", 550);
    create.add("iPwrFc", 9.1);

    // send data and get response
    ParseResponse response = create.send();

    // display response status
    Serial.println("\nResponse for saving LogData:");
    Serial.print(response.getJSONBody());
    if (!response.getErrorCode()) {
      String objectId = response.getString("objectId");
      Serial.print("Test object id:");
      Serial.println(objectId);
    } else {
      Serial.println("Failed to save the log data");
    }
    response.close();
  }
}

**Comment by ronaldyang** [comment] 2015-04-15 21:13
@cjevans76  Thanks for submitting the issue. We are looking at this problem. Please stay tuned.

**Comment by cjevans76** [comment] 2015-04-15 22:35
For reference, the available memory seems to decrease every 15 or so loops round, not every loop.  So with a minute between loops, it takes c. 15 minutes to see a drop in memory and c. an hour for the system to run out of memory altogether.

**Comment by ronaldyang** [comment] 2015-04-16 07:01
@cjevans76  The fix is in this commit https://github.com/ParsePlatform/parse-embedded-sdks/commit/aae4cb3a5d65e1fbc1299af97abe3ecfb30f215 
Let us know if the problem is still existing with this fix.

**Comment by cjevans76** [comment] 2015-04-16 08:33
@ronaldyang Thanks.  I'll have a look this evening and let you know.

**Comment by cjevans76** [comment] 2015-04-16 21:08
Looks good so far (albeit with limited testing).  I'll leave it running overnight to get a bit more data.
Thanks for the quick turn-around.

**Comment by cjevans76** [comment] 2015-04-17 06:50
Still running after 10 hours so looks fixed.

**Comment by ronaldyang** [comment] 2015-04-17 08:05
Sounds good. Closing this issue.

**Closed by ronaldyang** 2015-04-17 08:05 UTC

**Comment by oms5** [comment] 2015-08-15 02:33
Please update the [Starter Project Link](https://www.parse.com/downloads/arduino/ArduinoStarterProject-1.0.0.zip) with this fix in the [Quick Start guide](https://www.parse.com/apps/quickstart#embedded/arduinoyun).
